development:
  adapter: mysql2
  encoding: utf8
  database: booking_hotel
  pool: 5
  username: root
  password: khailee99
test:
  adapter: mysql2
  encoding: utf8
  database: booking_hotel
  pool: 5
  username: root
  password: khailee99
production:
  adapter: mysql2
  encoding: utf8
  database: booking_hotel
  pool: 5
  username: root
  password: khailee99
